/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env= --include-runtime=false --strict-vars=false` (hash: 1ff81ca7276f6d1f9bf7daba6cdda6c6)
interface __BaseEnv_Env {
	MCT_DB: D1Database;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	OWNER_EMAIL: string;
	ALLOWED_ORIGIN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface PreviewEnv {
		MCT_DB: D1Database;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
		OWNER_EMAIL: string;
		ALLOWED_ORIGIN: string;
	}
	interface ProductionEnv {
		MCT_DB: D1Database;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
		OWNER_EMAIL: string;
		ALLOWED_ORIGIN: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "OWNER_EMAIL" | "ALLOWED_ORIGIN">> {}
}
